### ISSUE TITLE
Проверить проект на соответствие минимальным требованиям к 1 ревью

### ISSUE THREAD

**Issue by val-hero** [val-hero/practicum-android-diploma#110]

**Comment by val-hero** [comment]
Необходимо доделать:

**Экран поиска.**

1. При удалении текста из строки поиск (стиранием или по иконке крестика) поисковый запрос всё равно выполняется. Должен отменяться.
2. Если не реализуется постраничная загрузка вакансий, то размер страницы при выполнении поискового запроса должен быть равен 50.

**Экран деталей вакансии**

1. Под названием компании должен отображаться её адрес. Если адреса нет, то должно отображаться название региона.


**Похожие вакансии**

1. Если для вакансии не было найдено похожих вакансий, то пользователь должен видеть соответствующий плейсхолдер.

**Избранное**

1. Пользователь может просматривать подробную информацию о вакансии без подключения к интернету. Он видит всё кроме логотипа и похожих вакансий. (нужно менять кнопку "похожих вакансий" в зависимости от наличия подключения к интернету)

**Comment by deiteriy** [comment]
ЗАДАЧИ НА РЕВЬЮ:

2. При нажатии на кнопку «Поделиться» открывается стандартный диалог для отправки ссылки на вакансию с hh.ru в выбранный пользователем мессенджер.
3. Нажатие на электронный адрес должно предлагать пользователю выбрать доступный на устройстве почтовый клиент для отправки электронного письма на этот адрес.
4. Нажатие на номер должно предлагать пользователю выбрать доступное
на устройстве приложение для осуществления звонков, чтобы позвонить по этому номеру.
